---
title: "Diversification"
output: html_document
---

```{r, cache=TRUE}
#install.packages(c("ape", "TreeSim", "geiger", "diversitree", "devtools"))
library(ape)
library(TreeSim)
library(geiger)
library(diversitree)
#devtools::install_github("thej022214/hisse")
library(hisse)


my.tree <- TreeSim::sim.bd.taxa(n=300, numbsim=1, lambda=0.1, mu=0)[[1]]
plot(my.tree)
ape::ltt.plot(my.tree)
ape::ltt.plot(my.tree, log="y")

yule.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=0.1, mu=0, complete=FALSE)
class(yule.trees) <- "multiPhylo"
ape::mltt.plot(yule.trees)

bd.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=1, mu=.9, complete=FALSE)
ape::mltt.plot(bd.trees, log="y", legend=FALSE)

depth.range <- range(unlist(lapply(yule.trees,ape::branching.times)), unlist(lapply(bd.trees,ape::branching.times)))
max.depth <- sum(abs(depth.range)) #ape rescales depths
plot(x=c(0, -1*max.depth), y=c(1, ape::Ntip(yule.trees[[1]])), log="y", type="n", bty="n", xlab="Time", ylab="N")
colors=c(rgb(1,0,0,0.5), rgb(0, 0, 0, 0.5))
list.of.both <- list(bd.trees, yule.trees)
for (i in sequence(2)) {
    tree.list <- list.of.both[[i]]
    for (j in sequence(length(tree.list))) {
        ape::ltt.lines(tree.list[[j]], col=colors[[i]])
    }
}
legend("topleft", legend=c("Birth Death", "Yule"), fill=colors)

depth.range <- range(unlist(lapply(yule.trees,ape::branching.times)), unlist(lapply(bd.trees,ape::branching.times)))
max.depth <- sum(abs(depth.range)) #ape rescales depths
plot(x=c(0, -5), y=c(200, ape::Ntip(yule.trees[[1]])), log="y", type="n", bty="n", xlab="Time", ylab="N")
colors=c(rgb(1,0,0,0.5), rgb(0, 0, 0, 0.5))
list.of.both <- list(bd.trees, yule.trees)
for (i in sequence(2)) {
    tree.list <- list.of.both[[i]]
    for (j in sequence(length(tree.list))) {
        ape::ltt.lines(tree.list[[j]], col=colors[[i]])
    }
}
legend("topleft", legend=c("Birth Death", "Yule"), fill=colors)

my.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=2, mu=.1, complete=FALSE)
other.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=3, mu=1.1, complete=FALSE)
more.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=1.8, mu=.3, complete=FALSE)
par(mfcol=c(2,2))
ape::mltt.plot(my.trees, log="y", legend=FALSE)
ape::mltt.plot(other.trees, log="y", legend=FALSE)
title(main = "Constant Difference")
ape::mltt.plot(more.trees, log="y", legend=FALSE)
title(main = "Same Total")

```

```{r}
library(diversitree)
speciation.rates <- c(0.1, 0.1, 0.1, 0.2) #0A, 1A, 0B, 1B
extinction.rates <- rep(0.03, 4)
transition.rates <- c(0.01,0.01,0, 0.01, 0, 0.01, 0.01,0,0.01, 0,0.01,0.01)
pars <- c(speciation.rates, extinction.rates, transition.rates)
phy <- NULL
while(is.null(phy)) { phy <- diversitree::tree.musse(pars, max.taxa=50, x0=1, include.extinct=FALSE) }
sim.dat.true <- data.frame(names(phy$tip.state), phy$tip.state)
sim.dat <- sim.dat.true
# Now to hide the "hidden" state
sim.dat[sim.dat[,2]==3,2] = 1
sim.dat[sim.dat[,2]==4,2] = 2
# and convert states 1,2 to 0,1
sim.dat[,2] = sim.dat[,2] - 1

plot(phy)
knitr::kable(cbind(sim.dat, true.char=sim.dat.true$phy.tip.state))
```
```{r, cache=TRUE}
turnover.anc = c(1,1,0,0)
eps.anc = c(1,1,0,0)

trans.rates = hisse::TransMatMaker(hidden.states=TRUE)
trans.rates

trans.rates.nodual = hisse::ParDrop(trans.rates, c(3,5,8,10))
trans.rates.nodual

trans.rates.nodual.equal16 = hisse::ParEqual(trans.rates.nodual, c(1,6))
trans.rates.nodual.equal16

trans.rates.nodual.allequal = hisse::ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8))
trans.rates.nodual.allequal

trans.rates.nodual.allequal = trans.rates.nodual
trans.rates.nodual.allequal[!is.na(trans.rates.nodual.allequal) & !trans.rates.nodual.allequal == 0] = 1
trans.rates.nodual.allequal

trans.rates.bisse = hisse::TransMatMaker(hidden.states=FALSE)
trans.rates.bisse

pp = hisse::hisse(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
           eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal)

turnover.anc = c(1,2,0,3)
eps.anc = c(1,2,0,3)

trans.rates <- hisse::TransMatMaker(hidden.states=TRUE)
trans.rates.nodual.no0B <- hisse::ParDrop(trans.rates, c(2,3,5,7,8,9,10,12))
trans.rates.nodual.no0B

pp = hisse::hisse(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
           eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal, output.type="net.div")
```
```{r}
turnover.anc = c(1,1,2,2)
eps.anc = c(1,1,2,2)

trans.rates = hisse::TransMatMaker(hidden.states=TRUE)
trans.rates.nodual = hisse::ParDrop(trans.rates, c(3,5,8,10))

trans.rates.nodual.allequal = hisse::ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8))
trans.rates.nodual.allequal

# Now we want three specific rates:
trans.rates.nodual.threerates <- trans.rates.nodual
# Set all transitions from 0->1 to be governed by a single rate:
to.change <- cbind(c(1,3), c(2,4))
trans.rates.nodual.threerates[to.change] = 1
# Now set all transitions from 1->0 to be governed by a single rate:
to.change <- cbind(c(2,4), c(1,3))
trans.rates.nodual.threerates[to.change] = 2
# Finally, set all transitions between the hidden state to be a single rate (essentially giving
# you an estimate of the rate by which shifts in diversification occur:
to.change <- cbind(c(1,3,2,4), c(3,1,4,2))
trans.rates.nodual.threerates[to.change] = 3
trans.rates.nodual.threerates

pp = hisse::hisse(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
           eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal)
```
```{r, cache=TRUE}
load("testrecon1.rda")
class(pp.recon)
pp.recon

hisse::plot.hisse.states(pp.recon, rate.param="net.div", show.tip.label=FALSE)

hisse::plot.hisse.states(pp.recon, rate.param="net.div", show.tip.label=FALSE, rate.range=c(0,0.072))

pp.recon$aic

pp.recon = hisse::MarginRecon(phy, sim.dat, f=c(1,1), hidden.states=TRUE, pars=pp$solution,
                       aic=pp$aic)

hisse.results.list = list()
load("testrecon1.rda")
hisse.results.list[[1]] = pp.recon
load("testrecon2.rda")
hisse.results.list[[2]] = pp.recon
load("testrecon3.rda")
hisse.results.list[[3]] = pp.recon
# Now supply the list the plotting function
hisse::plot.hisse.states(hisse.results.list, rate.param="net.div", show.tip.label=FALSE, rate.range=c(0,0.072))

#This stuff doesn't work because I have a PC.
# First, suck in all the files with .Rsave line ending in your working directory:
files = system("ls -1 | grep .rda", intern=TRUE)
# Create an empty list object
hisse.results.list = list()
# Now loop through all files, adding the embedded pp.recon object in each
for(i in sequence(length(files))){
  load(files[i])
  hisse.results.list[[i]] = pp.recon
  rm(pp.recon)
}

```
With my data:
```{r}
library(RCurl)
tree<-read.tree(text=getURL("https://raw.githubusercontent.com/lukejharmon/pcm/master/datafiles/squamate.phy"))
sqdata <- read.csv(text=getURL("https://raw.githubusercontent.com/lukejharmon/pcm/master/datafiles/brandley_table.csv"), row.names = 1, check.names = TRUE, stringsAsFactors = FALSE)
rownames(sqdata) <- sub(" ", "_", rownames(sqdata))

char_dat <- as.matrix(sqdata[,15])
rownames(char_dat) <- row.names(sqdata)
char_dat[char_dat[,1]==2,1] = 1

#I know from previous exerises that not all of the species in the tree line up with the data matrix.
CleanData <- function(phy, data) {
  geiger::treedata(phy = phy, data = data, sort = TRUE, warnings = TRUE)
}

cleaned_discrete <- CleanData(phy = tree, data = char_dat)

library(data.table)
chrono_tree <- ape::chronos(cleaned_discrete$phy)
clean_char_data <- data.table(cleaned_discrete$data, keep.rownames = TRUE)
clean_char <- as.data.frame(clean_char_data)
rownames(clean_char) <- row.names(cleaned_discrete$data)
head(clean_char)
```
Set up the tranisition rate matrix and diversification parameters:  
```{r}
trans_rates <- hisse::TransMatMaker(hidden.states=TRUE)
trans_rates_nodual_no0B <- hisse::ParDrop(trans_rates, c(2,3,5,7,8,9,10,12))
turnover_anc = c(1,2,0,3)
eps_anc = c(1,2,0,3)
```
Run Hisse:  
```{r, cache=TRUE}
myhisse <- hisse::hisse(chrono_tree, clean_char, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover_anc, eps.anc=eps_anc, trans.rate=trans_rates_nodual_no0B, output.type="net.div")
```
Plotting hisse reconstruction:  
```{r}
myhisse_recon <- hisse::MarginRecon(chrono_tree, clean_char, f=c(1,1), hidden.states=TRUE, pars=myhisse$solution, aic=myhisse$aic)

hisse::plot.hisse.states(myhisse_recon, rate.param="net.div", show.tip.label=FALSE)
```